_target_: torchvision.transforms.Compose
transforms:
  - _target_: torchvision.transforms.RandomHorizontalFlip
    p: 0.5
  - _target_: torchvision.transforms.RandomRotation
    degrees: 20
  - _target_: torchvision.transforms.ColorJitter
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.05
  - _target_: torchvision.transforms.RandomResizedCrop
    size: [224, 224]
    scale: [0.7, 1.0]
    ratio: [0.9, 1.1]
    interpolation: 2
  - _target_: torchvision.transforms.Resize
    size: [224, 224]
  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]