_target_: torchvision.transforms.Compose
transforms:
  - _target_: torchvision.transforms.RandomHorizontalFlip
    p: 0.5
  - _target_: torchvision.transforms.RandomRotation
    degrees: 5
  - _target_: torchvision.transforms.ColorJitter
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
    hue: 0.05
#  - _target_: torchvision.transforms.RandomErasing
#    p: 0.5
#    scale: [0.02,0.1]
#    ratio: [0.3, 3.3]
  - _target_: torchvision.transforms.Resize
    size: [224, 224]
  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
