wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.7
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683829949.62409
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 13
      - 23
      4: 3.7.7
      5: 0.15.2
      8:
      - 5
